version: 2.0

jobs:
  "php-5.6":
    docker:
      - image: circleci/php:5.6
    working_directory: ~/zipkin-doctrine
    steps:
      - checkout
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

  "php-7.0":
    docker:
      - image: circleci/php:7.0
    working_directory: ~/zipkin-doctrine
    steps:
      - checkout
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

  "php-7.1":
    docker:
      - image: circleci/php:7.1
    working_directory: ~/zipkin-doctrine
    steps:
      - checkout
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

  "php-7.2":
    docker:
      - image: circleci/php:7.2
    working_directory: ~/zipkin-doctrine
    steps:
      - checkout
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

workflows:
  version: 2
  build:
    jobs:
      - "php-5.6"
      - "php-7.0"
      - "php-7.1"
      - "php-7.2"
